services:
  clabbert-db:
    image: "postgres:17"
    container_name: clabbert-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clabbert
      - PGUSER=postgres # To fix fatal error "role "root" does not exist" when running pg_isready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "clabbert"]
      interval: 1s
      timeout: 1s
      retries: 5

  clabbert-app:
    image: "clabbert"
    build: .
    container_name: clabbert-app
    ports:
      - "8080:8080"
    depends_on:
      clabbert-db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=clabbert-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=clabbert
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - SERVER_PORT=8080 # If not set, the default port is 8080
      - LEPRECHAUN_IP=leprechaun
      - LEPRECHAUN_PORT=8080
      - INFERIUS_IP=inferius
      - INFERIUS_PORT=8080
