include:
  - "../jobberknoll/compose.yml"
services:
  feather-app:
    build:
      context: ".."
      dockerfile: "./feather/Dockerfile"
    ports:
      - "8001:8001"
    environment:
      SERVER_PORT: "8001"
      JOBBERKNOLL_SERVICE_HOST: "http://jobberknoll-app"
      JOBBERKNOLL_SERVICE_PORT: "8000"
