- name: Install required services for deployment
  hosts: deployment
  become: true
  tasks:
    - name: Install snap packages
      community.general.snap:
        name:
          - docker
          - aws-cli
        classic: true
        state: present

    - name: Install kubectl
      community.general.snap:
        name: kubectl
        state: present

    - name: Add docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker
        append: true

    - name: Change sock permissions
      ansible.builtin.file:
        dest: /var/run/docker.sock
        owner: root
        group: docker

    - name: Install minikube
      ansible.builtin.apt:
        deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        state: present
