server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  config:
    import: optional:classpath:env.properties
  cloud:
    gateway:
      routes:
        - id: accounts_route
          uri: http://${JOBBERKNOLL_SERVICE_HOST}:${JOBBERKNOLL_SERVICE_PORT}
          predicates:
            - Path=/api/account/**
          filters:
            - RewritePath=/api/account/(?<remaining>.*), /ext/${remaining}
            - AddRequestIdFilter
            - AddRequestHeader=user-agent, Phoenix/${phoenix.version}

        - id: tickets_route
          uri: http://${CLABBERT_SERVICE_HOST}:${CLABBERT_SERVICE_PORT}
          predicates:
            - Path=/api/ticket/**
          filters:
            - RewritePath=/api/ticket/(?<remaining>.*), /ext/${remaining}
            - AddRequestIdFilter
            - AddRequestHeader=user-agent, Phoenix/${phoenix.version}

        - id: payments_route
          uri: http://${INFERIUS_SERVICE_HOST}:${INFERIUS_SERVICE_PORT}
          predicates:
            - Path=/api/payment/**
          filters:
            - RewritePath=/api/payment/(?<remaining>.*), /ext/${remaining}
            - AddRequestIdFilter
            - AddRequestHeader=user-agent, Phoenix/${phoenix.version}

        - id: logistics_route
          uri: http://${LEPRECHAUN_SERVICE_HOST}:${LEPRECHAUN_SERVICE_PORT}
          predicates:
            - Path=/api/logistics/**
          filters:
            - RewritePath=/api/logistics/(?<remaining>.*), /ext/${remaining}
            - AddRequestIdFilter
            - AddRequestHeader=user-agent, Phoenix/${phoenix.version}