spring:
  application:
    name: clabbert
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true
    database: postgresql
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      base-path: /int/v1/
      exposure:
        include: "health"
  endpoint:
    health:
      enabled: true

springdoc:
  api-docs:
    path: /int/v1/docs/openapi
  swagger-ui:
    path: /int/v1/docs/swagger
