services:
  jobberknoll-app:
    build: "."
    ports:
      - "8000:8000"
    environment:
      PROD: "true"
      SERVER_PORT: "8000"
      DATABASE_URL: "postgres://postgres:password@jobberknoll-db:5432/postgres"
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:$$SERVER_PORT/int/v1/health"]
      interval: 1m
      timeout: 5s
      start_period: 10s
      start_interval: 1s
    depends_on:
      jobberknoll-db:
        condition: "service_healthy"
  jobberknoll-db:
    image: "postgres:17.0-alpine"
    environment:
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1m
      timeout: 5s
      start_period: 10s
      start_interval: 1s
