name: inferius-ci

on:
  push:
    branches:
      - main
    paths:
      - "implementation/inferius/**"
      - ".github/workflows/inferius.yml"
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
    paths:
      - "implementation/inferius/**"
      - ".github/workflows/inferius.yml"

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build and test project
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: implementation/inferius

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env.properties
        run: |
          echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> src/main/resources/env.properties
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> src/main/resources/env.properties
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> src/main/resources/env.properties
          echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> src/main/resources/env.properties
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> src/main/resources/env.properties
          echo INFERIUS_VERSION=${{ secrets.INFERIUS_VERSION }} >> src/main/resources/env.properties

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Run Build
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Run Integration Tests
        run: mvn failsafe:integration-test failsafe:verify